 
name: extraction
on:
  schedule:
    - cron: '*/5 * * * *'
    - cron: '49 15 * * *'
    - cron: '00 07 * * *'
    - cron: '30 10 * * *'
    - cron: '30 13 * * *'
    - cron: '00 16 * * *'
      
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Create local changes
        run: |
          git checkout -b PR
          git config --local user.email "geographesESR@protonmail.com"
          git config --local user.name "geographesESR"
          bash extraction.sh
          git add *
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: PR
          force: true  
      - uses: actions/checkout@v1
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "PR"                     # If blank, default: triggered branch
          destination_branch: "master"          # If blank, default: master
